'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class SystemMessages
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Trace.SystemMessages", GetType(SystemMessages).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;div class=&apos;validate-msg&apos;&gt;&lt;span class=&apos;k-icon k-i-warning&apos;&gt;&lt;/span&gt; Přístup není povolen&lt;/div&gt;.
        '''</summary>
        Public Shared ReadOnly Property AccessIsNotAllowed() As String
            Get
                Return ResourceManager.GetString("AccessIsNotAllowed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Účet povolen.
        '''</summary>
        Public Shared ReadOnly Property AccountAllowed() As String
            Get
                Return ResourceManager.GetString("AccountAllowed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Přidat nový záznam.
        '''</summary>
        Public Shared ReadOnly Property AddRecord() As String
            Get
                Return ResourceManager.GetString("AddRecord", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Platnost stánky vypršela, uživatel neexistuje nebo uživatel již má přidělené heslo...
        '''</summary>
        Public Shared ReadOnly Property ChangePasswordAlert() As String
            Get
                Return ResourceManager.GetString("ChangePasswordAlert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pole musí obsahovat:.
        '''</summary>
        Public Shared ReadOnly Property ChangePasswordT1() As String
            Get
                Return ResourceManager.GetString("ChangePasswordT1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nevolte hesla, která používáte na jiných webech nebo která lze snadno uhodnout..
        '''</summary>
        Public Shared ReadOnly Property ChangePasswordT10() As String
            Get
                Return ResourceManager.GetString("ChangePasswordT10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nevyplněno.
        '''</summary>
        Public Shared ReadOnly Property ChangePasswordT11() As String
            Get
                Return ResourceManager.GetString("ChangePasswordT11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Příliš mnoho stejných znaků za sebou..
        '''</summary>
        Public Shared ReadOnly Property ChangePasswordT12() As String
            Get
                Return ResourceManager.GetString("ChangePasswordT12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nevolte hesla, která používáte na jiných webech nebo která lze snadno uhodnout..
        '''</summary>
        Public Shared ReadOnly Property ChangePasswordT13() As String
            Get
                Return ResourceManager.GetString("ChangePasswordT13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Slabé.
        '''</summary>
        Public Shared ReadOnly Property ChangePasswordT14() As String
            Get
                Return ResourceManager.GetString("ChangePasswordT14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dobré.
        '''</summary>
        Public Shared ReadOnly Property ChangePasswordT15() As String
            Get
                Return ResourceManager.GetString("ChangePasswordT15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Silné.
        '''</summary>
        Public Shared ReadOnly Property ChangePasswordT16() As String
            Get
                Return ResourceManager.GetString("ChangePasswordT16", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Minimálně jeden znak.
        '''</summary>
        Public Shared ReadOnly Property ChangePasswordT2() As String
            Get
                Return ResourceManager.GetString("ChangePasswordT2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 8 nebo více znaků.
        '''</summary>
        Public Shared ReadOnly Property ChangePasswordT3() As String
            Get
                Return ResourceManager.GetString("ChangePasswordT3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Velká a malá písmena.
        '''</summary>
        Public Shared ReadOnly Property ChangePasswordT4() As String
            Get
                Return ResourceManager.GetString("ChangePasswordT4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Alespoň jedno číslo.
        '''</summary>
        Public Shared ReadOnly Property ChangePasswordT5() As String
            Get
                Return ResourceManager.GetString("ChangePasswordT5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stejné heslo jako předchozí.
        '''</summary>
        Public Shared ReadOnly Property ChangePasswordT6() As String
            Get
                Return ResourceManager.GetString("ChangePasswordT6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Správný email.
        '''</summary>
        Public Shared ReadOnly Property ChangePasswordT7() As String
            Get
                Return ResourceManager.GetString("ChangePasswordT7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unikátní email.
        '''</summary>
        Public Shared ReadOnly Property ChangePasswordT8() As String
            Get
                Return ResourceManager.GetString("ChangePasswordT8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Síla hesla:.
        '''</summary>
        Public Shared ReadOnly Property ChangePasswordT9() As String
            Get
                Return ResourceManager.GetString("ChangePasswordT9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Přejete si zrušit splátkový kalendář?.
        '''</summary>
        Public Shared ReadOnly Property ConfirmDeleteSK() As String
            Get
                Return ResourceManager.GetString("ConfirmDeleteSK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Smazat záznam.
        '''</summary>
        Public Shared ReadOnly Property DeleteRecordTitle() As String
            Get
                Return ResourceManager.GetString("DeleteRecordTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit.
        '''</summary>
        Public Shared ReadOnly Property EditRecordTitle() As String
            Get
                Return ResourceManager.GetString("EditRecordTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Soubor nenalezen.
        '''</summary>
        Public Shared ReadOnly Property FileNotFound() As String
            Get
                Return ResourceManager.GetString("FileNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nemůžete se přihlásit?.
        '''</summary>
        Public Shared ReadOnly Property ForgottenPassword() As String
            Get
                Return ResourceManager.GetString("ForgottenPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dobrý den, požadali jste o obnovení hesla. Tlačítkem níže budete přesměrován na stránku pro vytvoření Vašeho nového hesla..
        '''</summary>
        Public Shared ReadOnly Property forgPassEmailBody() As String
            Get
                Return ResourceManager.GetString("forgPassEmailBody", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Je prázdné.
        '''</summary>
        Public Shared ReadOnly Property IsEmpty() As String
            Get
                Return ResourceManager.GetString("IsEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Není prázdné.
        '''</summary>
        Public Shared ReadOnly Property IsNotEmpty() As String
            Get
                Return ResourceManager.GetString("IsNotEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Varování! Aplikace nedostala odpoved třetí strany (google api). Funkce google (mapy, gps ...) budou nedostupné.&lt;br&gt;Zkontrolujte připojení k síti. Pravděpodobně jste offline..
        '''</summary>
        Public Shared ReadOnly Property isOffLine() As String
            Get
                Return ResourceManager.GetString("isOffLine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;div class=&apos;validate-msg&apos;&gt;&lt;span class=&apos;k-icon k-i-warning&apos;&gt;&lt;/span&gt; Chybně zadané heslo nebo uživatelské jméno&lt;/div&gt;.
        '''</summary>
        Public Shared ReadOnly Property LoginWrong() As String
            Get
                Return ResourceManager.GetString("LoginWrong", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dobrý den, byl Vám vytvořen nový účet v aplikaci TRACE. Pro zdárné dokončení registrace je nutné si vytvořit vlastní heslo. Tlačítkem níže budete přesměrován na stránku pro vytvoření Vašeho nového hesla..
        '''</summary>
        Public Shared ReadOnly Property newPassEmailBody() As String
            Get
                Return ResourceManager.GetString("newPassEmailBody", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Novým uživatelům byl odeslán email s výzvou pro změnu hesla.
        '''</summary>
        Public Shared ReadOnly Property NewUsersPostEmail() As String
            Get
                Return ResourceManager.GetString("NewUsersPostEmail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stojíte na nezaškrtnutém spise, tento spis nebude zpracován. Pokračovat?.
        '''</summary>
        Public Shared ReadOnly Property NoCheckedItem() As String
            Get
                Return ResourceManager.GetString("NoCheckedItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Je vyžadováno vyplnění důvodu uzavření spisu.
        '''</summary>
        Public Shared ReadOnly Property NoComment1() As String
            Get
                Return ResourceManager.GetString("NoComment1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Je vyžadováno vyplnění důvodu proč přesunout spis k OSN.
        '''</summary>
        Public Shared ReadOnly Property NoComment2() As String
            Get
                Return ResourceManager.GetString("NoComment2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Je vyžadováno vyplnění důvodu žádosti o vrácení spisu.
        '''</summary>
        Public Shared ReadOnly Property NoComment3() As String
            Get
                Return ResourceManager.GetString("NoComment3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Je vyžadováno vyplnění komentáře.
        '''</summary>
        Public Shared ReadOnly Property NoComment4() As String
            Get
                Return ResourceManager.GetString("NoComment4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Je vyžadováno vyplnění důvodu změny D1MAX.
        '''</summary>
        Public Shared ReadOnly Property NoComment5() As String
            Get
                Return ResourceManager.GetString("NoComment5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Je vyžadováno vyplnění důvodu změny DMAX.
        '''</summary>
        Public Shared ReadOnly Property NoComment6() As String
            Get
                Return ResourceManager.GetString("NoComment6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vyplňte prosím datum.
        '''</summary>
        Public Shared ReadOnly Property NoDate() As String
            Get
                Return ResourceManager.GetString("NoDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vyberte spisy ke zpracování.
        '''</summary>
        Public Shared ReadOnly Property NoItems() As String
            Get
                Return ResourceManager.GetString("NoItems", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data nejsou k dispozici.
        '''</summary>
        Public Shared ReadOnly Property NoRecords() As String
            Get
                Return ResourceManager.GetString("NoRecords", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pokračovat.
        '''</summary>
        Public Shared ReadOnly Property PassEmailButton() As String
            Get
                Return ResourceManager.GetString("PassEmailButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Změna hesla.
        '''</summary>
        Public Shared ReadOnly Property PassEmailSubject() As String
            Get
                Return ResourceManager.GetString("PassEmailSubject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pole heslo nemůže být prázdné.
        '''</summary>
        Public Shared ReadOnly Property PassRequired() As String
            Get
                Return ResourceManager.GetString("PassRequired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Uživateli byl odeslán email s pokyny pro změnu hesla.
        '''</summary>
        Public Shared ReadOnly Property PostEmailUser() As String
            Get
                Return ResourceManager.GetString("PostEmailUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;div class=&apos;validate-msg&apos;&gt;&lt;span class=&apos;k-icon k-i-warning&apos;&gt;&lt;/span&gt; Nebylo možné odeslat email ke změně hesla, protože uživatel s tímto emailem nebyl nalezen&lt;/div&gt;.
        '''</summary>
        Public Shared ReadOnly Property PostUsesNotFound() As String
            Get
                Return ResourceManager.GetString("PostUsesNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dobrý den, někdo požádal o změnu vašeho hesla do aplikace TRACE. Pokud jste o změnu nežádali, tento email ignorujte. Jinak tlačítkem níže budete přesměrován na stránku pro změnu Vašeho hesla..
        '''</summary>
        Public Shared ReadOnly Property resetPassEmailBody() As String
            Get
                Return ResourceManager.GetString("resetPassEmailBody", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resetování uživatelského hesla a odeslání emailu s výzvou ke změně hesla..
        '''</summary>
        Public Shared ReadOnly Property ResetPasswordTitle() As String
            Get
                Return ResourceManager.GetString("ResetPasswordTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hotovo.
        '''</summary>
        Public Shared ReadOnly Property Success() As String
            Get
                Return ResourceManager.GetString("Success", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to musí být unikátní.
        '''</summary>
        Public Shared ReadOnly Property Unique() As String
            Get
                Return ResourceManager.GetString("Unique", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;div class=&apos;validate-msg&apos;&gt;&lt;span class=&apos;k-icon k-i-warning&apos;&gt;&lt;/span&gt; Uživatel nenalezen&lt;/div&gt;.
        '''</summary>
        Public Shared ReadOnly Property UseNotFound() As String
            Get
                Return ResourceManager.GetString("UseNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pole email nemůže být prázdné.
        '''</summary>
        Public Shared ReadOnly Property UserLoginRequired() As String
            Get
                Return ResourceManager.GetString("UserLoginRequired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Upozornění.
        '''</summary>
        Public Shared ReadOnly Property Warning() As String
            Get
                Return ResourceManager.GetString("Warning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chybná emailová adresa.
        '''</summary>
        Public Shared ReadOnly Property WrongEmail() As String
            Get
                Return ResourceManager.GetString("WrongEmail", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
