'------------------------------------------------------------------------------
' <auto-generated>
'    Tento kód byl generován ze šablony.
'
'    Ruční změny tohoto souboru mohou způsobit neočekávané chování v aplikaci.
'    Ruční změny tohoto souboru budou přepsány, pokud bude kód vygenerován znovu.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblAAALog
    Public Property ID As Integer
    Public Property IDSpisu As Nullable(Of Integer)
    Public Property Identifikace As String
    Public Property Data As String
    Public Property cas As Date

End Class
