'------------------------------------------------------------------------------
' <auto-generated>
'    Tento kód byl generován ze šablony.
'
'    Ruční změny tohoto souboru mohou způsobit neočekávané chování v aplikaci.
'    Ruční změny tohoto souboru budou přepsány, pokud bude kód vygenerován znovu.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblCampaign
    Public Property IDCampaign As Integer
    Public Property rr_CampType As Short
    Public Property CampDateCreated As Date
    Public Property CampName As String
    Public Property rr_CampState As Byte
    Public Property CampDescription As String
    Public Property DeadLine As Nullable(Of Date)
    Public Property IDUser As Integer
    Public Property PercentDone As Single

End Class
