'------------------------------------------------------------------------------
' <auto-generated>
'    Tento kód byl generován ze šablony.
'
'    Ruční změny tohoto souboru mohou způsobit neočekávané chování v aplikaci.
'    Ruční změny tohoto souboru budou přepsány, pokud bude kód vygenerován znovu.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblCampMember
    Public Property IDCampMember As Integer
    Public Property IDCampaign As Integer
    Public Property IDSpisyOsobyAdresy As Integer
    Public Property IDSpisyOsoby As Nullable(Of Integer)
    Public Property MemberOrder As Nullable(Of Integer)
    Public Property rr_CampMemberState As Byte
    Public Property IDVisitReport As Nullable(Of Integer)
    Public Property rr_CampAddrType As Byte

End Class
