'------------------------------------------------------------------------------
' <auto-generated>
'    Tento kód byl generován ze šablony.
'
'    Ruční změny tohoto souboru mohou způsobit neočekávané chování v aplikaci.
'    Ruční změny tohoto souboru budou přepsány, pokud bude kód vygenerován znovu.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblCampRouteTrajectory
    Public Property IDTraj As Long
    Public Property IDUser As Integer
    Public Property GPSLat As Nullable(Of Single)
    Public Property GPSLng As Nullable(Of Single)

End Class
