'------------------------------------------------------------------------------
' <auto-generated>
'    Tento kód byl generován ze šablony.
'
'    Ruční změny tohoto souboru mohou způsobit neočekávané chování v aplikaci.
'    Ruční změny tohoto souboru budou přepsány, pokud bude kód vygenerován znovu.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblExternalAddress
    Public Property IDExternalAddress As Integer
    Public Property IDUser As Integer
    Public Property ExtAddrName As String
    Public Property ExtAddrStreet As String
    Public Property ExtAddrHouseNum As String
    Public Property ExtAddrZipCode As String
    Public Property ExtAddrCity As String
    Public Property ExtAddrRegion As String
    Public Property GPSLat As String
    Public Property GPSLng As String
    Public Property GPSValid As Boolean
    Public Property ExtAddrComment As String
    Public Property AddrLocalGovernment As Nullable(Of Boolean)

End Class
