'------------------------------------------------------------------------------
' <auto-generated>
'    Tento kód byl generován ze šablony.
'
'    Ruční změny tohoto souboru mohou způsobit neočekávané chování v aplikaci.
'    Ruční změny tohoto souboru budou přepsány, pokud bude kód vygenerován znovu.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblKompost
    Public Property IDKompost As Integer
    Public Property IDUser As Nullable(Of Integer)
    Public Property IDSpisu As Nullable(Of Integer)
    Public Property ObjectXML As String
    Public Property IsSubObject As Nullable(Of Boolean)
    Public Property Head As Nullable(Of Boolean)
    Public Property [Date] As Date

End Class
