'------------------------------------------------------------------------------
' <auto-generated>
'    Tento kód byl generován ze šablony.
'
'    Ruční změny tohoto souboru mohou způsobit neočekávané chování v aplikaci.
'    Ruční změny tohoto souboru budou přepsány, pokud bude kód vygenerován znovu.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblObjectAccessibility
    Public Property IDObjectAccessibility As Integer
    Public Property Destination As String
    Public Property [Object] As String
    Public Property IDObject As String
    Public Property Access As Nullable(Of Short)
    Public Property None As Boolean
    Public Property One As Boolean
    Public Property More As Boolean
    Public Property Param4 As Boolean
    Public Property Param5 As Boolean
    Public Property Param6 As Boolean
    Public Property Param7 As Boolean
    Public Property Param8 As Boolean

End Class
