'------------------------------------------------------------------------------
' <auto-generated>
'    Tento kód byl generován ze šablony.
'
'    Ruční změny tohoto souboru mohou způsobit neočekávané chování v aplikaci.
'    Ruční změny tohoto souboru budou přepsány, pokud bude kód vygenerován znovu.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblOSNUnfinished
    Public Property IDUser As Integer
    Public Property Ordering As Integer
    Public Property [Object] As String
    Public Property ObjectXML As String
    Public Property Finished As Boolean
    Public Property IDSpisu As Integer
    Public Property IsSubObject As Boolean
    Public Property Head As Boolean
    Public Property rr_IDFVProcess As Nullable(Of Byte)

End Class
