'------------------------------------------------------------------------------
' <auto-generated>
'    Tento kód byl generován ze šablony.
'
'    Ruční změny tohoto souboru mohou způsobit neočekávané chování v aplikaci.
'    Ruční změny tohoto souboru budou přepsány, pokud bude kód vygenerován znovu.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblOSNObjectDefinition
    Public Property [Object] As String
    Public Property ObjectSource As String
    Public Property CaseVariable As String
    Public Property Comment As String
    Public Property PracovniXML As String
    Public Property rr_IDFVProcess As Nullable(Of Byte)
    Public Property IsSubObject As Boolean
    Public Property Head As Boolean

End Class
