'------------------------------------------------------------------------------
' <auto-generated>
'    Tento kód byl generován ze šablony.
'
'    Ruční změny tohoto souboru mohou způsobit neočekávané chování v aplikaci.
'    Ruční změny tohoto souboru budou přepsány, pokud bude kód vygenerován znovu.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblRole
    Public Property IDRole As Integer
    Public Property RoleName As String
    Public Property Authorize As String

    Public Overridable Property tblUsers As ICollection(Of tblUser) = New HashSet(Of tblUser)

End Class
