'------------------------------------------------------------------------------
' <auto-generated>
'    Tento kód byl generován ze šablony.
'
'    Ruční změny tohoto souboru mohou způsobit neočekávané chování v aplikaci.
'    Ruční změny tohoto souboru budou přepsány, pokud bude kód vygenerován znovu.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblUradyCiselnik
    Public Property IDUradu As Integer
    Public Property AdresaUradu As String
    Public Property GPSLatUradu As String
    Public Property GPSLngUradu As String
    Public Property HASHUradu As String

End Class
