'------------------------------------------------------------------------------
' <auto-generated>
'    Tento kód byl generován ze šablony.
'
'    Ruční změny tohoto souboru mohou způsobit neočekávané chování v aplikaci.
'    Ruční změny tohoto souboru budou přepsány, pokud bude kód vygenerován znovu.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblUser
    Public Property IDUser As Integer
    Public Property IDRole As Integer
    Public Property UserFirstName As String
    Public Property UserLastName As String
    Public Property UserLogin As String
    Public Property UserPWD As String
    Public Property UserMobilePhone As String
    Public Property UserInternalID As Nullable(Of Integer)
    Public Property UserAccountEnabled As Boolean
    Public Property PDFPWD As String
    Public Property AndroidLastCall As Nullable(Of Date)
    Public Property BadLoginsCount As Short
    Public Property BadLoginsBlock As Boolean
    Public Property LoginBlockTime As Nullable(Of Date)
    Public Property PasswordValidityBegin As Nullable(Of Date)
    Public Property PasswordValidityEndBlock As Boolean
    Public Property AndroidVersion As String
    Public Property AndroidVersionUpdate As Nullable(Of Date)

    Public Overridable Property tblRole As tblRole

End Class
