'------------------------------------------------------------------------------
' <auto-generated>
'    Tento kód byl generován ze šablony.
'
'    Ruční změny tohoto souboru mohou způsobit neočekávané chování v aplikaci.
'    Ruční změny tohoto souboru budou přepsány, pokud bude kód vygenerován znovu.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vw_CreditorTemplates
    Public Property IDCreditor As Integer
    Public Property CreditorAlias As String
    Public Property TemplateDLSpis As String
    Public Property TemplateFVLetter As String
    Public Property TemplateUZSK As String

End Class
