'------------------------------------------------------------------------------
' <auto-generated>
'    Tento kód byl generován ze šablony.
'
'    Ruční změny tohoto souboru mohou způsobit neočekávané chování v aplikaci.
'    Ruční změny tohoto souboru budou přepsány, pokud bude kód vygenerován znovu.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vw_Constant1
    Public Property ConstantName As String
    Public Property rr_ConstantType As String
    Public Property ConstantValue As String
    Public Property ConstantUnit As String
    Public Property ConstantDescription As String
    Public Property IDOrder As Nullable(Of Short)

End Class
