'------------------------------------------------------------------------------
' <auto-generated>
'    Tento kód byl generován ze šablony.
'
'    Ruční změny tohoto souboru mohou způsobit neočekávané chování v aplikaci.
'    Ruční změny tohoto souboru budou přepsány, pokud bude kód vygenerován znovu.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vw_CampCompare_GPS_Date
    Public Property IDUser As Nullable(Of Integer)
    Public Property IDSpisu As Integer
    Public Property ACC As String
    Public Property UserLastName As String
    Public Property VR1_DateOSN As Nullable(Of Date)
    Public Property DocuSentDate As Nullable(Of Date)
    Public Property Rozdil_DatumOSN_Foto As Nullable(Of Integer)
    Public Property FVAddrGPSLat As String
    Public Property FVAddrGPSLng As String
    Public Property DocGPSLat As String
    Public Property DocGPSLng As String
    Public Property VR1_GPSLat As String
    Public Property VR1_GPSLng As String
    Public Property Vzdalenost_AddrOSN_Zapis As Nullable(Of Double)
    Public Property Vzdalenost_AddrOSN_Foto As Nullable(Of Double)
    Public Property DatumZapisu As Nullable(Of Date)
    Public Property Rozdil_DatumOSN_DatumZapisu As Nullable(Of Integer)
    Public Property IDVisitReport As Integer

End Class
