'------------------------------------------------------------------------------
' <auto-generated>
'    Tento kód byl generován ze šablony.
'
'    Ruční změny tohoto souboru mohou způsobit neočekávané chování v aplikaci.
'    Ruční změny tohoto souboru budou přepsány, pokud bude kód vygenerován znovu.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vw_ListReminders
    Public Property Radek As Nullable(Of Long)
    Public Property Type As String
    Public Property IDCase As Nullable(Of Integer)
    Public Property CreatedDate As Nullable(Of Date)
    Public Property Txt As String
    Public Property ReminderDeadline As Nullable(Of Date)
    Public Property IDUser As Nullable(Of Integer)
    Public Property ID As Integer

End Class
