'------------------------------------------------------------------------------
' <auto-generated>
'    Tento kód byl generován ze šablony.
'
'    Ruční změny tohoto souboru mohou způsobit neočekávané chování v aplikaci.
'    Ruční změny tohoto souboru budou přepsány, pokud bude kód vygenerován znovu.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vw_Users
    Public Property IDUser As Integer
    Public Property IDRole As Integer
    Public Property UserFirstName As String
    Public Property UserLastName As String
    Public Property UserLogin As String
    Public Property UserPWD As String
    Public Property UserMobilePhone As String
    Public Property UserInternalID As Nullable(Of Integer)

End Class
