'------------------------------------------------------------------------------
' <auto-generated>
'    Tento kód byl generován ze šablony.
'
'    Ruční změny tohoto souboru mohou způsobit neočekávané chování v aplikaci.
'    Ruční změny tohoto souboru budou přepsány, pokud bude kód vygenerován znovu.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vwA1_KeZprac
    Public Property IDSpisu As Integer
    Public Property IDUser As Integer
    Public Property AlertExist As Integer
    Public Property ACC As String
    Public Property rr_State As Short
    Public Property StateTxt As String
    Public Property PersSurname As String
    Public Property PersName As String
    Public Property PersRC As String
    Public Property PersIC As String
    Public Property PersBirthDate As Nullable(Of Date)
    Public Property CreditorAlias As String
    Public Property PersRegion As String
    Public Property PersCity As String
    Public Property PersStreet As String
    Public Property PersHouseNum As String
    Public Property PersZipCode As String
    Public Property LastDebtContacted As Nullable(Of Date)
    Public Property GPSValid As Boolean
    Public Property PersPhone As String
    Public Property DateReturnToCreditor As Nullable(Of Date)
    Public Property DateLapse As Nullable(Of Date)
    Public Property IDSpisyOsobyAdresy As Integer
    Public Property IDSpisyOsoby As Integer
    Public Property MinDatum As Nullable(Of Date)
    Public Property AddrLocalGovernment As Boolean
    Public Property DebtLastOSN As Nullable(Of Date)

End Class
