'------------------------------------------------------------------------------
' <auto-generated>
'    Tento kód byl generován ze šablony.
'
'    Ruční změny tohoto souboru mohou způsobit neočekávané chování v aplikaci.
'    Ruční změny tohoto souboru budou přepsány, pokud bude kód vygenerován znovu.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vwA1_Novy
    Public Property IDSpisu As Integer
    Public Property IDUser As Integer
    Public Property AlertExist As Integer
    Public Property ACC As String
    Public Property PersSurname As String
    Public Property PersName As String
    Public Property PersRC As String
    Public Property PersIC As String
    Public Property PersRegion As String
    Public Property PersBirthDate As Nullable(Of Date)
    Public Property CreditorAlias As String
    Public Property ActualDebit As Nullable(Of Double)
    Public Property PersCity As String
    Public Property PersStreet As String
    Public Property PersHouseNum As String
    Public Property PersZipCode As String
    Public Property VisitDateSentFromMother As Nullable(Of Date)
    Public Property GPSValid As Nullable(Of Boolean)
    Public Property rr_State As Short
    Public Property PersPhone As String
    Public Property IDSpisyOsoby As Nullable(Of Integer)
    Public Property IDSpisyOsobyAdresy As Nullable(Of Integer)
    Public Property VisitDateD1Max As Nullable(Of Date)
    Public Property StateTxt As String
    Public Property rr_Currency As String
    Public Property CurrencyTxt As String
    Public Property DMAX As Nullable(Of Date)
    Public Property VisitDatePlan As Nullable(Of Date)
    Public Property GPSValidDetail As Nullable(Of Byte)
    Public Property AddrLocalGovernment As Nullable(Of Boolean)

End Class
