'------------------------------------------------------------------------------
' <auto-generated>
'    Tento kód byl generován ze šablony.
'
'    Ruční změny tohoto souboru mohou způsobit neočekávané chování v aplikaci.
'    Ruční změny tohoto souboru budou přepsány, pokud bude kód vygenerován znovu.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vwA1_Finished
    Public Property IDSpisu As Integer
    Public Property IDUser As Integer
    Public Property AlertExist As Integer
    Public Property ACC As String
    Public Property PersSurname As String
    Public Property PersName As String
    Public Property CreditorAlias As String
    Public Property VisitDateSentToMother As Nullable(Of Date)
    Public Property UserWhoClosedFile As String
    Public Property ReasonClosedFile As String
    Public Property PersIC As String
    Public Property ActualDebit As Nullable(Of Double)
    Public Property SumPaymentsByFV As Nullable(Of Double)
    Public Property AllCommissionPerFile As Nullable(Of Double)
    Public Property VisitDateReceiveFromMother As Nullable(Of Date)
    Public Property PersRC As String
    Public Property PersBirthDate As Nullable(Of Date)
    Public Property StateTxt As String
    Public Property rr_State As Short
    Public Property VisitDateSentFromMother As Nullable(Of Date)
    Public Property rr_Currency As String
    Public Property CurrencyTxt As String
    Public Property FV_TerminationDate As Nullable(Of Date)

End Class
