'------------------------------------------------------------------------------
' <auto-generated>
'    Tento kód byl generován ze šablony.
'
'    Ruční změny tohoto souboru mohou způsobit neočekávané chování v aplikaci.
'    Ruční změny tohoto souboru budou přepsány, pokud bude kód vygenerován znovu.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vwA2_DLKeZpracSub
    Public Property IDSpisu As Nullable(Of Integer)
    Public Property IDUser As Nullable(Of Integer)
    Public Property ACC As String
    Public Property AlertExist As Integer
    Public Property CreditorAlias As String
    Public Property ActualDebit As Nullable(Of Double)
    Public Property rr_State As Nullable(Of Short)
    Public Property StateTxt As String
    Public Property GPSValid As Nullable(Of Boolean)
    Public Property IDSpisyOsoby As Nullable(Of Integer)
    Public Property IDSpisyOsobyAdresy As Nullable(Of Integer)
    Public Property MinDatum As Nullable(Of Date)
    Public Property rr_Currency As String
    Public Property CurrencyTxt As String

End Class
