'------------------------------------------------------------------------------
' <auto-generated>
'    Tento kód byl generován ze šablony.
'
'    Ruční změny tohoto souboru mohou způsobit neočekávané chování v aplikaci.
'    Ruční změny tohoto souboru budou přepsány, pokud bude kód vygenerován znovu.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vwA2_DLDohodySub
    Public Property IDSpisu As Integer
    Public Property IDUser As Integer
    Public Property ACC As String
    Public Property AlertExist As Integer
    Public Property CreditorAlias As String
    Public Property ActualDebit As Nullable(Of Double)
    Public Property rr_PAValidityType As Nullable(Of Short)
    Public Property ValidityTypeTxt As String
    Public Property NextPaymentDate As Nullable(Of Date)
    Public Property NextPaymentAmountAwait As Nullable(Of Double)
    Public Property LastPaymentDate As Nullable(Of Date)
    Public Property LastPaymentAmountAwait As Nullable(Of Double)
    Public Property GPSValid As Nullable(Of Boolean)
    Public Property IDSpisyOsoby As Nullable(Of Integer)
    Public Property IDSpisyOsobyAdresy As Nullable(Of Integer)
    Public Property rr_Currency As String
    Public Property CurrencyTxt As String
    Public Property rr_State As Short

End Class
