'------------------------------------------------------------------------------
' <auto-generated>
'    Tento kód byl generován ze šablony.
'
'    Ruční změny tohoto souboru mohou způsobit neočekávané chování v aplikaci.
'    Ruční změny tohoto souboru budou přepsány, pokud bude kód vygenerován znovu.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vwA2_DLOSN
    Public Property IDSpisyOsoby As Integer
    Public Property AlertExist As Nullable(Of Integer)
    Public Property IDSrcSpisyOsoby As Nullable(Of Long)
    Public Property PersSurname As String
    Public Property PersName As String
    Public Property PersRC As String
    Public Property PersIC As String
    Public Property PersBirthDate As Nullable(Of Date)
    Public Property SumActualDebit As Nullable(Of Double)
    Public Property PersPhone As String
    Public Property PersRegion As String
    Public Property PersCity As String
    Public Property PersStreet As String
    Public Property PersHouseNum As String
    Public Property PersZipCode As String
    Public Property VisitDatePlan As Nullable(Of Date)
    Public Property IDSpisyOsobyAdresy As Nullable(Of Integer)
    Public Property GPSValid As Nullable(Of Boolean)
    Public Property VisitDatePlanNoChange As Nullable(Of Boolean)
    Public Property IDUser As Integer
    Public Property AddrLocalGovernment As Nullable(Of Boolean)

End Class
