'------------------------------------------------------------------------------
' <auto-generated>
'    Tento kód byl generován ze šablony.
'
'    Ruční změny tohoto souboru mohou způsobit neočekávané chování v aplikaci.
'    Ruční změny tohoto souboru budou přepsány, pokud bude kód vygenerován znovu.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vwAD_DLBasicSub
    Public Property IDSpisu As Integer
    Public Property IDSpisyOsoby As Integer
    Public Property IDUser As Integer
    Public Property AlertExist As Integer
    Public Property ACC As String
    Public Property CreditorAlias As String
    Public Property ActualDebit As Nullable(Of Double)
    Public Property rr_State As Short
    Public Property StateTxt As String
    Public Property FVDateSentFromMother As Nullable(Of Date)
    Public Property IDSpisyOsobyAdresy As Integer

End Class
