'------------------------------------------------------------------------------
' <auto-generated>
'    Tento kód byl generován ze šablony.
'
'    Ruční změny tohoto souboru mohou způsobit neočekávané chování v aplikaci.
'    Ruční změny tohoto souboru budou přepsány, pokud bude kód vygenerován znovu.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vwAD_BasicNonAccepted
    Public Property IDSpisu As Integer
    Public Property IDUser As Integer
    Public Property IDCreditor As Nullable(Of Integer)
    Public Property ACC As String
    Public Property ActualDebit As Nullable(Of Double)
    Public Property UserLastName As String
    Public Property VisitDateSentFromMother As Nullable(Of Date)
    Public Property LL_LastLapse As Nullable(Of Short)
    Public Property FirstLapse As Nullable(Of Date)
    Public Property LastLapse As Nullable(Of Date)
    Public Property LastLapseMsg As String

End Class
