'------------------------------------------------------------------------------
' <auto-generated>
'    Tento kód byl generován ze šablony.
'
'    Ruční změny tohoto souboru mohou způsobit neočekávané chování v aplikaci.
'    Ruční změny tohoto souboru budou přepsány, pokud bude kód vygenerován znovu.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vwSpisyPlatbyPred1OSN
    Public Property IDSpisyPlatbyDosle As Integer
    Public Property IDSpisu As Integer
    Public Property PaymentDate As Nullable(Of Date)
    Public Property Amount As Nullable(Of Double)
    Public Property CommissionForIP As Nullable(Of Double)

End Class
